### ISSUE TITLE
it should work for cracked

### ISSUE THREAD

**Issue by knixle** [CloaksPlus/NewInstaller#5]
the cloaks plus servers and stuff should be allowed for cracked players

**Comment by Wesley51** [comment]
This isn't an issue, buy the game

**Comment by tmrxdev** [comment]
This is not an issue, you need to buy the game or suggest it

**Comment by SeizureSaladd** [comment]
First of all, we physically can't make it work for cracked Minecraft users as their user account doesn't actually exist and the bot adds cloaks based off of UUIDs. Secondly, using cracked Minecraft is a form of piracy, and Cloaks+ does not support piracy. Cy supporting cracked Minecraft we would be directly supporting piracy, which is a crime, and you would also be violating Mojang's EULA.
