### ISSUE TITLE
Make it available for MacOS and Linux

### ISSUE THREAD

**Issue by EinfachRuwen** [CloaksPlus/NewInstaller#6]
Hello,
I am a Linux-User and I would love to use Cloaks+ but I can't. Using Wine, it wouldn't work and it's kinda annoying me, so please make it available for MacOS and/or Linux.

**Comment by SeizureSaladd** [comment]
Hey! You can use Cloaks+ on macOS and Linux by following the specific installation steps for those operating systems in our Discord server! To install on Linux, go to our Linux installation channel under the Installation category.
